#!/usr/bin/env python3
"""Export key HRs and cohort stats to docs/manuscript/manuscript_stats.tex."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

MANUSCRIPT_DIR = REPO / "docs" / "manuscript"
FIG_TABLES = REPO / "figures" / "manuscript" / "tables"
ANALYSIS_OUT = REPO / "data" / "processed" / "analysis"


def _hr_fmt(hr: float, lo: float, hi: float, p: float | None = None) -> str:
    s = f"{hr:.3f} (95\\% CI {lo:.3f}--{hi:.3f})"
    if p is not None:
        if p < 0.001:
            s += ", $p<0.001$"
        else:
            s += f", $p={p:.3f}$"
    return s


def _pick_m4(df: pd.DataFrame, term_sub: str, level: str | None = None) -> tuple[float, float, float, float]:
    sub = df[df["term"].astype(str).str.contains(term_sub, na=False)]
    if level:
        sub = sub[
            sub["term"].astype(str).str.contains(level, na=False)
            | sub["comparison"].astype(str).str.contains(level, na=False)
        ]
    if sub.empty and term_sub == "initial_pain_score":
        sub = df[df["term"] == "initial_pain_score"]
    if sub.empty:
        return (float("nan"),) * 4
    r = sub.iloc[0]
    return float(r["hazard_ratio"]), float(r["ci_low"]), float(r["ci_high"]), float(r["pvalue"])


def _pick_seq(df: pd.DataFrame, factor: str, model: str) -> tuple[float, float, float, float]:
    sub = df[(df["factor"] == factor) & (df["model"] == model) & (df["in_model"] == True)]
    if sub.empty:
        return (float("nan"),) * 4
    r = sub.iloc[0]
    return float(r["hazard_ratio"]), float(r["ci_low"]), float(r["ci_high"]), float(r["pvalue"])


def main() -> None:
    flow = json.loads((ANALYSIS_OUT / "flow_counts.json").read_text())
    m4 = pd.read_csv(FIG_TABLES / "table06_m4_sectional_forest.csv")
    seq = pd.read_csv(FIG_TABLES / "table08_sequential_attenuation.csv")
    within = pd.read_csv(ANALYSIS_OUT / "within_acuity_key_hrs.csv")
    severe = pd.read_csv(FIG_TABLES / "table12_severe_pain_key_hrs.csv")
    year = pd.read_csv(FIG_TABLES / "table_year_continuous_model.csv")

    def m4cmd(name: str, term: str, level: str | None = None) -> str:
        hr, lo, hi, p = _pick_m4(m4, term, level)
        return f"\\newcommand{{\\{name}}}{{{_hr_fmt(hr, lo, hi, p)}}}\n"

    lines = [
        "% Auto-generated by scripts/export_manuscript_stats.py — do not edit by hand\n",
        f"\\newcommand{{\\CohortN}}{{{flow['primary_analytic_cohort']:,}}}\n",
        f"\\newcommand{{\\CohortEvents}}{{{flow['reassessment_events']:,}}}\n",
        f"\\newcommand{{\\FlowAllED}}{{{flow['all_ed_stays_in_extract']:,}}}\n",
        m4cmd("HRPainMfour", "initial_pain_score"),
        m4cmd("HRESIMfour", "triage_acuity"),
        m4cmd("HRAmbulanceMfour", "arrival_mode", "ambulance"),
        m4cmd("HRNightMfour", "arrival_shift", "night"),
        m4cmd("HRMedicaidMfour", "insurance_group", "Medicaid"),
        m4cmd("HRMedicareMfour", "insurance_group", "Medicare"),
        m4cmd("HRBlackMfour", "race_ethnicity", "Black"),
        m4cmd("HRHispanicMfour", "race_ethnicity", "Hispanic"),
        m4cmd("HRAsianMfour", "race_ethnicity", "Asian"),
    ]

    for factor, model, cmd in [
        ("Medicaid vs private", "M2", "HRMedicaidMtwo"),
        ("Medicaid vs private", "M3", "HRMedicaidMthree"),
        ("Medicaid vs private", "M4", "HRMedicaidMfourSeq"),
        ("Black vs White", "M2", "HRBlackMtwo"),
        ("Black vs White", "M4", "HRBlackMfourSeq"),
    ]:
        hr, lo, hi, p = _pick_seq(seq, factor, model)
        lines.append(f"\\newcommand{{\\{cmd}}}{{{_hr_fmt(hr, lo, hi, p)}}}\n")

    for esi, cmd in [("ESI 1–2", "HRMedicaidESI12"), ("ESI 3", "HRMedicaidESI3")]:
        sub = within[
            (within["esi_group"] == esi)
            & within["term"].astype(str).str.contains("insurance_group")
            & within["comparison"].astype(str).str.contains("Medicaid")
        ]
        if len(sub):
            r = sub.iloc[0]
            lines.append(
                f"\\newcommand{{\\{cmd}}}{{{_hr_fmt(r['hazard_ratio'], r['ci_low'], r['ci_high'], r['pvalue'])}}}\n"
            )

    sub = severe[severe["comparison"].astype(str).str.contains("Medicaid")].head(1)
    if len(sub):
        r = sub.iloc[0]
        lines.append(
            f"\\newcommand{{\\HRMedicaidSevere}}{{{_hr_fmt(r['hazard_ratio'], r['ci_low'], r['ci_high'], r['pvalue'])}}}\n"
        )
    sub = severe[severe["comparison"].astype(str).str.contains("Black")].head(1)
    if len(sub):
        r = sub.iloc[0]
        lines.append(
            f"\\newcommand{{\\HRBlackSevere}}{{{_hr_fmt(r['hazard_ratio'], r['ci_low'], r['ci_high'], r['pvalue'])}}}\n"
        )

    if len(year):
        r = year.iloc[0]
        lines.append(
            f"\\newcommand{{\\HRYearFive}}{{{r['hazard_ratio_per_5_years']:.3f} "
            f"(95\\% CI {r['ci_low_per_5_years']:.3f}--{r['ci_high_per_5_years']:.3f}, "
            f"$p={r['pvalue_per_1_year']:.3f}$)}}\n"
        )

    out = MANUSCRIPT_DIR / "manuscript_stats.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(lines))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
